version: '3'

services:
  app:
    container_name: JamesApp
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - mongo
  mongo:
    container_name: mongobd
    image: mongo
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - ./data:/data/db
      - ./data/log:/var/log/mongodb/
         